# This file was generated by GoReleaser. DO NOT EDIT.
cask "k3d-router" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f207ede7fa22647829c1b3098fdee2b0b947d0a1017a7883e6aedc4c6042f378"
      url "https://github.com/foundry23/k3d-router/releases/download/v#{version}/k3d-router_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "47b60f3c832f1c823f9b282a9f2cb795bae8d736040bab4804f9fe4e81c53211"
      url "https://github.com/foundry23/k3d-router/releases/download/v#{version}/k3d-router_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "863c54479825bc59aa8b13bec7c39fefa819c87be56672b904bd2d2b47eecf57"
      url "https://github.com/foundry23/k3d-router/releases/download/v#{version}/k3d-router_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bd9747283c2f6148ff1441b1ec6cd0416b54d9fbf56613d7b983aa75f7073f8"
      url "https://github.com/foundry23/k3d-router/releases/download/v#{version}/k3d-router_#{version}_linux_arm64.tar.gz"
    end
  end

  name "k3d-router"
  desc "A shared local reverse proxy for k3d clusters"
  homepage "https://github.com/foundry23/k3d-router"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k3d-router"

  # No zap stanza required

end
