# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glaze < Formula
  desc "Convert git porcelain to JSON"
  homepage "https://github.com/foundry23/glaze"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foundry23/glaze/releases/download/v0.1.0/glaze_0.1.0_darwin_amd64.tar.gz"
      sha256 "8e795a6ed953ce0e4bc43633658d38fa2dfe7d73f8e9ac4b0a93df678b5dfbfa"

      define_method(:install) do
        bin.install "glaze"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foundry23/glaze/releases/download/v0.1.0/glaze_0.1.0_darwin_arm64.tar.gz"
      sha256 "d63c5b55d8825bf0d445bc4a28764d50f41509dcb5cceceaaebac0a2e971a6cf"

      define_method(:install) do
        bin.install "glaze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/glaze/releases/download/v0.1.0/glaze_0.1.0_linux_amd64.tar.gz"
      sha256 "1a4d409935b2b3fc09ea5910e7b4743598f564dae459a80730b9b211d2f85b5b"
      define_method(:install) do
        bin.install "glaze"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/glaze/releases/download/v0.1.0/glaze_0.1.0_linux_arm64.tar.gz"
      sha256 "e3220d57db1ffa244143adeae233fee2a4f94a1139c335a366db1dd4e9218167"
      define_method(:install) do
        bin.install "glaze"
      end
    end
  end
end
