# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glaze < Formula
  desc "Convert git porcelain to JSON"
  homepage "https://github.com/foundry23/glaze"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foundry23/glaze/releases/download/v0.1.1/glaze_0.1.1_darwin_amd64.tar.gz"
      sha256 "94410ef37a526a69b3338d7b5f3d7a88a659a7ac500888d6d55dc281e8eb7d4a"

      define_method(:install) do
        bin.install "glaze"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foundry23/glaze/releases/download/v0.1.1/glaze_0.1.1_darwin_arm64.tar.gz"
      sha256 "34da7f5e9178e96d6656a17c207a159991f7ba676b21b1fbe32fe01f7320b475"

      define_method(:install) do
        bin.install "glaze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/glaze/releases/download/v0.1.1/glaze_0.1.1_linux_amd64.tar.gz"
      sha256 "944db86c685c27ca6c0f85fae7de15aa03faa1c391ce421cb244f6b8691e6820"
      define_method(:install) do
        bin.install "glaze"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/glaze/releases/download/v0.1.1/glaze_0.1.1_linux_arm64.tar.gz"
      sha256 "66fff3aa2f79c38be7d50d847d4c77b52f8dec2d5ff9073d43c0e3fe42f809f7"
      define_method(:install) do
        bin.install "glaze"
      end
    end
  end
end
