# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3dRouter < Formula
  desc "A shared local reverse proxy for k3d clusters"
  homepage "https://github.com/foundry23/k3d-router"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foundry23/k3d-router/releases/download/v0.1.1/k3d-router_0.1.1_darwin_amd64.tar.gz"
      sha256 "e77329b50b4e62291b29ebffc776a0fd76294a4b776803c718c8bc2d76089a13"

      define_method(:install) do
        bin.install "k3d-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foundry23/k3d-router/releases/download/v0.1.1/k3d-router_0.1.1_darwin_arm64.tar.gz"
      sha256 "020d195edbb17c05ef7afc78b027f4f5c06656df54f8603f39b470ed27c12144"

      define_method(:install) do
        bin.install "k3d-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/k3d-router/releases/download/v0.1.1/k3d-router_0.1.1_linux_amd64.tar.gz"
      sha256 "2f309379a7e816e7cf7d80183d9fee32e78ada3f332157e1c62c7f34b67b6ffb"
      define_method(:install) do
        bin.install "k3d-router"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/k3d-router/releases/download/v0.1.1/k3d-router_0.1.1_linux_arm64.tar.gz"
      sha256 "82c319b1f71536c06f3040231659e766a5beba86c1c33c80c47180e3f0f3b568"
      define_method(:install) do
        bin.install "k3d-router"
      end
    end
  end

  def caveats
    <<~EOS
      k3d-router talks to your Docker engine — make sure Docker/OrbStack is running.
    EOS
  end

  service do
    run [opt_bin/"k3d-router", "watch"]
    keep_alive true
    log_path var/"log/k3d-router.log"
    error_log_path var/"log/k3d-router.log"
  end
end
