# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3dRouter < Formula
  desc "A shared local reverse proxy for k3d clusters"
  homepage "https://github.com/foundry23/k3d-router"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foundry23/k3d-router/releases/download/v0.2.1/k3d-router_0.2.1_darwin_amd64.tar.gz"
      sha256 "a5d3b7054c496d4f8737e4354b179379c78def019e0daea013ecb8bf894df9fb"

      define_method(:install) do
        bin.install "k3d-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foundry23/k3d-router/releases/download/v0.2.1/k3d-router_0.2.1_darwin_arm64.tar.gz"
      sha256 "0eb91efa51c2a07e48aa816353ff2960de8075e5deee8de6bb35ec49acd0dc18"

      define_method(:install) do
        bin.install "k3d-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/k3d-router/releases/download/v0.2.1/k3d-router_0.2.1_linux_amd64.tar.gz"
      sha256 "240a7fa8a86c775f6a6c969a571ef6672429eaed84a06a193153a5ba7a5c568e"
      define_method(:install) do
        bin.install "k3d-router"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/k3d-router/releases/download/v0.2.1/k3d-router_0.2.1_linux_arm64.tar.gz"
      sha256 "1db9949d713b8e44348a0593107265f2e9a4888c23d576ce41003c335f4e488f"
      define_method(:install) do
        bin.install "k3d-router"
      end
    end
  end

  def caveats
    <<~EOS
      k3d-router requires your docker engine to be running.
    EOS
  end

  service do
    run [opt_bin/"k3d-router", "watch"]
    keep_alive true
    log_path var/"log/k3d-router.log"
    error_log_path var/"log/k3d-router.log"
  end
end
