# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Switchboard < Formula
  desc "The missing control panel for your project; every switch runs a command"
  homepage "https://github.com/foundry23/switchboard"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foundry23/switchboard/releases/download/v0.1.0/switchboard_0.1.0_darwin_amd64.tar.gz"
      sha256 "898a731a1c403af09f6fc5adb773852626c287316748c792f0641d5044bb5ebd"

      define_method(:install) do
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foundry23/switchboard/releases/download/v0.1.0/switchboard_0.1.0_darwin_arm64.tar.gz"
      sha256 "6099c4a90a467e1f333ff41baf7905687665d23731e21e10a927946cea9ab5ad"

      define_method(:install) do
        bin.install "switchboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/switchboard/releases/download/v0.1.0/switchboard_0.1.0_linux_amd64.tar.gz"
      sha256 "b74a7371078cbd88ade3afe908743b3d1844299104be5517facb46f320353f7b"
      define_method(:install) do
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/switchboard/releases/download/v0.1.0/switchboard_0.1.0_linux_arm64.tar.gz"
      sha256 "439c3dd34406ad6571bffc374fde5eb8acba3b09b14a94a1c902de706504b137"
      define_method(:install) do
        bin.install "switchboard"
      end
    end
  end
end
