# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Switchboard < Formula
  desc "The missing control panel for your project; every switch runs a command"
  homepage "https://github.com/foundry23/switchboard"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foundry23/switchboard/releases/download/v0.1.1/switchboard_0.1.1_darwin_amd64.tar.gz"
      sha256 "7a86ebbf9c4c258afdc3a28cdb01f9d21e76c27e0df5a26dcf6402c5748e8a1e"

      define_method(:install) do
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foundry23/switchboard/releases/download/v0.1.1/switchboard_0.1.1_darwin_arm64.tar.gz"
      sha256 "c4e50a7bdb4ba093039a4b048e644987db107f1b8b48672dbdb15a0bf159ea98"

      define_method(:install) do
        bin.install "switchboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/switchboard/releases/download/v0.1.1/switchboard_0.1.1_linux_amd64.tar.gz"
      sha256 "8fc7e4cdb533eae415368cdd422ff1107eecac7f3d3d310933c13f5985e56f98"
      define_method(:install) do
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foundry23/switchboard/releases/download/v0.1.1/switchboard_0.1.1_linux_arm64.tar.gz"
      sha256 "dcf8b7fcc71e1a9f7f473e4091dcda60e4027367ca6dcc6c407495e6261b6270"
      define_method(:install) do
        bin.install "switchboard"
      end
    end
  end
end
